name: 'deploy to PyPI'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.?[ab]?[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Install build dependencies
        run: pip install build

      - name: Build
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION_FOR_jjava: ${{ github.ref_name }}
        run: |
          mvn clean verify -U
          python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/

  deploy:
    name: Deploy to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jjava
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Deploy distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
