name: 'release packages'

on:
  release:
    types: [published]

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: jjava-!(kernelspec)*@(.tar.gz|.whl)
          out-file-path: dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
