name: 'release packages'

on:
  release:
    types: [published]

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: jjava-!(kernelspec)*@(.tar.gz|.whl)
          out-file-path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: ${{ runner.debug }}

  release-homebrew:
    runs-on: ubuntu-latest

    steps:
      - name: Publish package to Homebrew
        uses: m-dzianishchyts/brewtap@v1
        with:
          homebrew_owner: m-dzianishchyts
          homebrew_tap: homebrew-jjava
          version: ${{ github.ref_name }}
          depends_on: |
            "jupyterlab"
            "java"
          target: jjava-${{ github.ref_name }}-kernelspec.zip
          install: |
            libexec.install Dir["*"]
            system "jupyter kernelspec install #{libexec} --sys-prefix --name=java "
          test: |
            jjava_version = Formula["jjava"].version
            jupyter = Formula["jupyterlab"].opt_bin/"jupyter"
            ENV["JUPYTER_PATH"] = share/"jupyter"

            assert_match " java ", shell_output("#{jupyter} kernelspec list")

            (testpath/"console.exp").write <<~EOS
              spawn #{jupyter} console --kernel=java
              expect -timeout 30 "In "
              send "System.out.println(\\\"Hello world!\\\");\r"
              expect -timeout 10 "In "
              send "\u0004"
              expect -timeout 10 "exit"
              send "y\r"
            EOS
            output = shell_output("expect -f console.exp")
            assert_match "JJava kernel #{jjava_version}", output
            assert_match "Hello world!", output
          update_readme_table: true
          github_token: ${{ secrets.HOMEBREW_REPO_ACCESS_TOKEN }}
          debug: ${{ runner.debug }}
