name: 'release packages'

on:
  release:
    types: [published]

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jjava
    permissions:
      id-token: write

    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: jjava-!(kernelspec)*@(.tar.gz|.whl)
          out-file-path: dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: ${{ runner.debug }}

  release-homebrew:
    runs-on: ubuntu-latest

    steps:
      - name: Publish to Homebrew
        uses: m-dzianishchyts/brewtap@v1
        with:
          homebrew_owner: m-dzianishchyts
          homebrew_tap: homebrew-jjava
          formula_folder: Formula
          version: ${{ github.ref_name }}
          depends_on: 'jupyterlab'
          target: jjava-${{ github.ref_name }}-kernelspec.zip
          install: 'system "jupyter kernelspec install #{Dir.pwd} --name=java --user"'
          update_readme_table: true
          commit_owner: github-actions[bot]
          commit_email: 41898282+github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.HOMEBREW_REPO_ACCESS_TOKEN }}
          debug: ${{ runner.debug }}
